trigger:
  branches:
    include:
      - nonroot

pool:
  name: self-hosted-linux

# 🔐 Variable group
variables:
- group: acr-secrets

- name: acrName
  value: day1sample
- name: imageName
  value: dotnet-monolith
- name: tag
  value: $(Build.BuildId)
- name: buildConfiguration
  value: Release

steps:
# =========================
# 📥 CHECKOUT
# =========================
- checkout: self
  fetchDepth: 0

# =========================
# 🔍 SONARCLOUD PREPARE (v4)
# =========================
- task: SonarCloudPrepare@4
  displayName: Prepare SonarCloud Analysis
  inputs:
    SonarCloud: 'sonarcloud-connection'
    organization: 'vishwa2102'
    scannerMode: 'dotnet'
    projectKey: 'vishwasureshkumar9950121_aks-zero-touch'
    projectName: 'dotnet-monolith'

# =========================
# 📦 RESTORE
# =========================
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '**/*.csproj'

# =========================
# 🏗 BUILD (MANDATORY FOR SONAR)
# =========================
- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--c
