apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"

  
    userAssignedIdentityID: "4b81a54a-bf3d-491b-ae4c-9595242b647e"

    keyvaultName: devopsdemovishva
    tenantId: b44a81f2-3485-4f65-9a34-bee75733d8cb
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
