grafana:
  adminPassword: admin123
  service:
    type: ClusterIP
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true

prometheus:
  prometheusSpec:
    retention: 10d
    scrapeInterval: 15s
    externalUrl: http://20.40.125.197/prometheus
    routePrefix: /prometheus
